"""
Load ATS company slugs from vendored jobhive CSVs + curated hot_slugs.txt.

Replaces the hardcoded GREENHOUSE_SLUGS / LEVER_SLUGS / ASHBY_SLUGS lists that
used to live in fetcher.py. Firestore is intentionally NOT the slug source —
at 10K slugs × 12 runs/day that would be 120K reads/day.

Tiers:
  hot   — ~270 curated slugs (from hot_slugs.txt), crawled every 2h
  cold  — everything in the jobhive CSVs that isn't hot, crawled daily
  all   — hot + cold, for the one-shot backfill script

Sharding:
  Deterministic slug-hash mod M split so 4-shard cold-tier crawls in a GH
  Actions matrix workflow. `shard=(0, 4)` means "shard 0 of 4."
"""
from __future__ import annotations

import csv
import hashlib
import logging
from functools import lru_cache
from pathlib import Path
from typing import Iterable, Optional

logger = logging.getLogger(__name__)

DATA_DIR = Path(__file__).parent / "data" / "ats_companies"
SUPPORTED_ATS = ("greenhouse", "lever", "ashby")


def _csv_path(ats: str) -> Path:
    return DATA_DIR / f"{ats}.csv"


def _hot_slugs_path() -> Path:
    return DATA_DIR / "hot_slugs.txt"


def _extras_path() -> Path:
    return DATA_DIR / "extras.txt"


def _parse_ats_slug_file(path: Path, label: str) -> dict[str, set[str]]:
    """Shared parser for hot_slugs.txt and extras.txt (`ats:slug` per line)."""
    result: dict[str, set[str]] = {a: set() for a in SUPPORTED_ATS}
    if not path.exists():
        return result
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        # Allow trailing comments after two spaces (e.g. "greenhouse:stripe  # Stripe")
        line = line.split("  #", 1)[0].strip()
        if ":" not in line:
            logger.warning("%s malformed line ignored: %r", label, line)
            continue
        ats, slug = line.split(":", 1)
        ats, slug = ats.strip().lower(), slug.strip()
        if ats not in SUPPORTED_ATS:
            logger.warning("%s unknown ats %r on line %r", label, ats, line)
            continue
        if slug:
            result[ats].add(slug)
    return result


@lru_cache(maxsize=None)
def _load_hot_slugs() -> dict[str, frozenset[str]]:
    """Parse hot_slugs.txt into {ats: frozenset[slug]}. Cached per process."""
    parsed = _parse_ats_slug_file(_hot_slugs_path(), "hot_slugs.txt")
    if not any(parsed.values()):
        logger.warning("hot_slugs.txt missing or empty — hot tier is empty")
    return {a: frozenset(s) for a, s in parsed.items()}


@lru_cache(maxsize=None)
def _load_extras() -> dict[str, frozenset[str]]:
    """Parse extras.txt — ancillary slug sources beyond jobhive (SimplifyJobs,
    YC directory pulls, etc.). Merged into the cold tier at load time.

    Kept separate from hot_slugs.txt because extras get regenerated by the
    weekly SimplifyJobs cron; treating them as first-class hot would fight
    that automation.
    """
    parsed = _parse_ats_slug_file(_extras_path(), "extras.txt")
    return {a: frozenset(s) for a, s in parsed.items()}


@lru_cache(maxsize=None)
def _load_csv(ats: str) -> tuple[dict[str, str], ...]:
    """Parse the jobhive CSV for one ATS. Returns tuple of {name, slug, url} dicts.

    Tuple (not list) so lru_cache returns an immutable view.
    """
    if ats not in SUPPORTED_ATS:
        raise ValueError(f"unsupported ats: {ats!r}")
    path = _csv_path(ats)
    if not path.exists():
        logger.warning("%s csv missing at %s", ats, path)
        return ()
    records: list[dict[str, str]] = []
    with path.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            slug = (row.get("slug") or "").strip()
            if not slug:
                continue
            records.append({
                "slug": slug,
                "name": (row.get("name") or "").strip(),
                "url": (row.get("url") or "").strip(),
            })
    logger.info("%s csv loaded: %d records", ats, len(records))
    return tuple(records)


def _in_shard(slug: str, shard: Optional[tuple[int, int]]) -> bool:
    """Deterministic hash-mod split. shard=(0, 4) → shard 0 of 4."""
    if shard is None:
        return True
    idx, total = shard
    if total <= 1:
        return True
    if not (0 <= idx < total):
        raise ValueError(f"shard idx {idx} out of range for total {total}")
    h = int(hashlib.md5(slug.encode()).hexdigest(), 16)
    return (h % total) == idx


def load_slugs(
    ats: str,
    tier: str = "hot",
    shard: Optional[tuple[int, int]] = None,
) -> list[str]:
    """Return the slug list for one ATS × tier, optionally sharded.

    tier: "hot" | "cold" | "all"
    shard: (idx, total) — for splitting cold-tier crawl across a GH Actions matrix.
           Hot tier ignores shard (small enough to always crawl fully in one job).
    """
    if ats not in SUPPORTED_ATS:
        raise ValueError(f"unsupported ats: {ats!r}")
    if tier not in ("hot", "cold", "all"):
        raise ValueError(f"unsupported tier: {tier!r}")

    hot = _load_hot_slugs()[ats]
    extras = _load_extras()[ats]

    if tier == "hot":
        # Hot tier is small; never shard.
        return sorted(hot)

    csv_slugs = [r["slug"] for r in _load_csv(ats)]
    if tier == "cold":
        # Union of jobhive CSV + extras (SimplifyJobs / YC / etc.), minus hot
        # (hot gets crawled on the 2h cadence separately — don't double-crawl).
        candidates = list((set(csv_slugs) | extras) - hot)
    else:  # all
        candidates = list({*csv_slugs, *hot, *extras})

    if shard is not None:
        candidates = [s for s in candidates if _in_shard(s, shard)]

    return sorted(candidates)


@lru_cache(maxsize=None)
def _name_map(ats: str) -> dict[str, str]:
    """Slug → canonical company name from jobhive CSV. Cached per process."""
    return {r["slug"]: r["name"] for r in _load_csv(ats) if r["name"]}


def get_company_name(ats: str, slug: str) -> str:
    """Canonical company display name for (ats, slug).

    Falls back to titlecased slug if the CSV lacks the entry — protects the
    hot tier if a curated slug isn't in jobhive yet.
    """
    name = _name_map(ats).get(slug)
    if name:
        return name
    return slug.replace("-", " ").replace("_", " ").title()


def load_all_records(ats: str) -> Iterable[dict[str, str]]:
    """Full {slug, name, url} records for one ATS — used by the seed script."""
    return _load_csv(ats)


def clear_cache() -> None:
    """Test helper: reset the module-level LRU caches."""
    _load_hot_slugs.cache_clear()
    _load_extras.cache_clear()
    _load_csv.cache_clear()
    _name_map.cache_clear()
