import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { ArrowRight, ArrowLeft, GraduationCap, Check, ChevronsUpDown } from "lucide-react";
import academicIllustration from "@/assets/academic-illustration.png";
import { cn } from "@/lib/utils";

interface AcademicData {
  university: string;
  degree: string;
  major: string;
  graduationMonth: string;
  graduationYear: string;
}

interface OnboardingAcademicsProps {
  onNext: (data: AcademicData) => void;
  onBack: () => void;
  initialData?: AcademicData;
}

// Total universities: 1019
const universities = [
  "Abilene Christian University",
  "Academy of Art University",
  "Adams State University",
  "Adelphi University",
  "Adrian College",
  "Agnes Scott College",
  "Alabama A&M University",
  "Alabama State University",
  "Albertus Magnus College",
  "Albion College",
  "Albright College",
  "Alcorn State University",
  "Alfred University",
  "Allegheny College",
  "Alliant International University",
  "Alma College",
  "Alverno College",
  "American International College",
  "American University",
  "Amherst College",
  "Anderson University (IN)",
  "Anderson University (SC)",
  "Angelo State University",
  "Anna Maria College",
  "Antioch University",
  "Appalachian State University",
  "Aquinas College",
  "Arcadia University",
  "Arizona State University",
  "Arizona State University Online",
  "Armstrong State University",
  "ArtCenter College of Design",
  "Asbury University",
  "Assumption University",
  "Auburn University",
  "Augsburg University",
  "Augustana College (IL)",
  "Augustana University (SD)",
  "Austin College",
  "Ave Maria University",
  "Azusa Pacific University",
  "BYU-Hawaii",
  "BYU-Idaho",
  "Babson College",
  "Baker University",
  "Baldwin Wallace University",
  "Ball State University",
  "Barnard College",
  "Barry University",
  "Bates College",
  "Bay Path University",
  "Baylor University",
  "Becker College",
  "Bellarmine University",
  "Belmont University",
  "Beloit College",
  "Bemidji State University",
  "Benedict College",
  "Benedictine College",
  "Benedictine University",
  "Bennett College",
  "Bennington College",
  "Bentley University",
  "Berea College",
  "Berklee College of Music",
  "Berry College",
  "Bethel College (KS)",
  "Bethel University (IN)",
  "Bethel University (MN)",
  "Bethune-Cookman University",
  "Biola University",
  "Birmingham-Southern College",
  "Black Hills State University",
  "Bloomsburg University",
  "Bob Jones University",
  "Boise State University",
  "Boston College",
  "Boston University",
  "Bowdoin College",
  "Bowie State University",
  "Bradley University",
  "Brandeis University",
  "Brandman University",
  "Briar Cliff University",
  "Bridgewater State University",
  "Brigham Young University (BYU)",
  "Brown University",
  "Bryan College",
  "Bryant University",
  "Bryn Mawr College",
  "Bucknell University",
  "Buena Vista University",
  "Butler University",
  "CSU Bakersfield",
  "CSU Channel Islands",
  "CSU Chico",
  "CSU Dominguez Hills",
  "CSU East Bay",
  "CSU Fullerton",
  "CSU Long Beach",
  "CSU Los Angeles",
  "CSU Monterey Bay",
  "CSU Northridge",
  "CSU San Bernardino",
  "CSU San Marcos",
  "CSU Stanislaus",
  "CUNY Baruch College",
  "CUNY Borough of Manhattan Community College",
  "CUNY Bronx Community College",
  "CUNY Brooklyn College",
  "CUNY City College of New York",
  "CUNY College of Staten Island",
  "CUNY Graduate Center",
  "CUNY Guttman Community College",
  "CUNY Hostos Community College",
  "CUNY Hunter College",
  "CUNY John Jay College of Criminal Justice",
  "CUNY Kingsborough Community College",
  "CUNY LaGuardia Community College",
  "CUNY Lehman College",
  "CUNY Macaulay Honors College",
  "CUNY Medgar Evers College",
  "CUNY New York City College of Technology",
  "CUNY Queens College",
  "CUNY Queensborough Community College",
  "CUNY York College",
  "Cabrini University",
  "Cal Poly Pomona",
  "Cal Poly San Luis Obispo",
  "Caldwell University",
  "California Baptist University",
  "California College of the Arts",
  "California Institute of Technology (Caltech)",
  "California Institute of the Arts (CalArts)",
  "California Lutheran University",
  "California University of Pennsylvania",
  "Calvin University",
  "Cameron University",
  "Canisius University",
  "Capella University",
  "Capital University",
  "Carleton College",
  "Carnegie Mellon University",
  "Carroll College (MT)",
  "Carroll University",
  "Carson-Newman University",
  "Carthage College",
  "Case Western Reserve University",
  "Castleton University",
  "Catholic University of America",
  "Centenary College of Louisiana",
  "Centenary University",
  "Central College",
  "Central Connecticut State University",
  "Central Methodist University",
  "Central Michigan University",
  "Central Washington University",
  "Centre College",
  "Chadron State College",
  "Chapman University",
  "Charleston Southern University",
  "Charter Oak State College",
  "Chatham University",
  "Cheyney University",
  "Christopher Newport University",
  "Claflin University",
  "Claremont Graduate University",
  "Claremont McKenna College",
  "Clarion University",
  "Clark Atlanta University",
  "Clark University",
  "Clarke University",
  "Clarkson University",
  "Clayton State University",
  "Clemson University",
  "Cleveland Institute of Art",
  "Coastal Carolina University",
  "Coe College",
  "Colburn School",
  "Colby College",
  "Colgate University",
  "College of Charleston",
  "College of Idaho",
  "College of Saint Benedict",
  "College of William & Mary",
  "College of Wooster",
  "College of the Holy Cross",
  "Colorado College",
  "Colorado Mesa University",
  "Colorado School of Mines",
  "Colorado State University",
  "Colorado Technical University",
  "Columbia College Chicago",
  "Columbia University",
  "Columbus College of Art and Design",
  "Columbus State University",
  "Concordia College (Moorhead)",
  "Concordia College (St. Paul)",
  "Concordia University Chicago",
  "Concordia University Irvine",
  "Concordia University Nebraska",
  "Concordia University Wisconsin",
  "Connecticut College",
  "Converse University",
  "Cooper Union",
  "Coppin State University",
  "Cornell College",
  "Cornell University",
  "Cornerstone University",
  "Cornish College of the Arts",
  "Covenant College",
  "Cranbrook Academy of Art",
  "Creighton University",
  "Crown College",
  "Culver-Stockton College",
  "Curry College",
  "Curtis Institute of Music",
  "D'Youville University",
  "Daemen University",
  "Dakota State University",
  "Dalton State College",
  "Dartmouth College",
  "Davidson College",
  "DePaul University",
  "DePauw University",
  "DeVry University",
  "Delaware State University",
  "Delaware Valley University",
  "Denison University",
  "Dickinson College",
  "Dickinson State University",
  "Dillard University",
  "Dixie State University",
  "Doane University",
  "Dominican University (IL)",
  "Dominican University of California",
  "Dordt University",
  "Drake University",
  "Drew University",
  "Drexel University",
  "Drury University",
  "Duke University",
  "Duquesne University",
  "Earlham College",
  "East Carolina University",
  "East Central University",
  "East Stroudsburg University",
  "Eastern Connecticut State University",
  "Eastern Illinois University",
  "Eastern Michigan University",
  "Eastern Nazarene College",
  "Eastern New Mexico University",
  "Eastern Oregon University",
  "Eastern Washington University",
  "Eastman School of Music",
  "Eckerd College",
  "Edgewood College",
  "Edinboro University",
  "Elizabeth City State University",
  "Elizabethtown College",
  "Elmhurst University",
  "Elms College",
  "Elon University",
  "Embry-Riddle Aeronautical University",
  "Embry-Riddle Aeronautical University (Prescott)",
  "Emerson College",
  "Emory University",
  "Emporia State University",
  "Endicott College",
  "Erskine College",
  "Eureka College",
  "Evangel University",
  "Evergreen State College",
  "Excelsior College",
  "Fairfield University",
  "Fairleigh Dickinson University",
  "Fashion Institute of Technology (FIT)",
  "Fayetteville State University",
  "Felician University",
  "Ferris State University",
  "Fisk University",
  "Fitchburg State University",
  "Flagler College",
  "Florida A&M University",
  "Florida Atlantic University",
  "Florida Gulf Coast University",
  "Florida International University",
  "Florida Southern College",
  "Florida State University",
  "Fontbonne University",
  "Fordham University",
  "Fort Hays State University",
  "Fort Lewis College",
  "Fort Valley State University",
  "Framingham State University",
  "Francis Marion University",
  "Franklin & Marshall College",
  "Franklin College",
  "Fresno Pacific University",
  "Fresno State University",
  "Friends University",
  "Frostburg State University",
  "Full Sail University",
  "Furman University",
  "Gallaudet University",
  "Gannon University",
  "George Fox University",
  "George Mason University",
  "George Washington University",
  "Georgetown University",
  "Georgia College & State University",
  "Georgia Institute of Technology",
  "Georgia Southern University",
  "Georgia Southwestern State University",
  "Georgia State University",
  "Georgian Court University",
  "Gettysburg College",
  "Gonzaga University",
  "Goodwin University",
  "Gordon College",
  "Gordon State College",
  "Goshen College",
  "Goucher College",
  "Grace College",
  "Graceland University",
  "Grambling State University",
  "Grand Canyon University",
  "Grand Valley State University",
  "Grand View University",
  "Greenville University",
  "Grinnell College",
  "Gustavus Adolphus College",
  "Gwynedd Mercy University",
  "Hamilton College",
  "Hamline University",
  "Hampshire College",
  "Hampton University",
  "Hanover College",
  "Hardin-Simmons University",
  "Harding University",
  "Harris-Stowe State University",
  "Hartwick College",
  "Harvard University",
  "Harvey Mudd College",
  "Hastings College",
  "Haverford College",
  "Hendrix College",
  "Heritage University",
  "Hillsdale College",
  "Hiram College",
  "Hobart and William Smith Colleges",
  "Hofstra University",
  "Holy Names University",
  "Hood College",
  "Hope College",
  "Hope International University",
  "Howard Payne University",
  "Howard University",
  "Humboldt State University",
  "Huntington University",
  "Huston-Tillotson University",
  "Idaho State University",
  "Illinois Institute of Technology",
  "Illinois State University",
  "Illinois Wesleyan University",
  "Immaculata University",
  "Indiana State University",
  "Indiana University Bloomington",
  "Indiana University East",
  "Indiana University Kokomo",
  "Indiana University Northwest",
  "Indiana University South Bend",
  "Indiana University Southeast",
  "Indiana University of Pennsylvania",
  "Indiana University-Purdue University Indianapolis (IUPUI)",
  "Indiana Wesleyan University",
  "Iowa State University",
  "Ithaca College",
  "Jackson State University",
  "Jacksonville University",
  "James Madison University",
  "John Brown University",
  "John Carroll University",
  "Johns Hopkins University",
  "Johnson & Wales University",
  "Johnson C. Smith University",
  "Johnson State College",
  "Juilliard School",
  "Kalamazoo College",
  "Kansas City Art Institute",
  "Kansas State University",
  "Kean University",
  "Keene State College",
  "Keiser University",
  "Kennesaw State University",
  "Kentucky State University",
  "Kenyon College",
  "King's College",
  "Knox College",
  "Kutztown University",
  "La Salle University",
  "La Sierra University",
  "LaGrange College",
  "Lafayette College",
  "Laguna College of Art and Design",
  "Lake Forest College",
  "Lake Superior State University",
  "Lamar University",
  "Lander University",
  "Lane College",
  "Langston University",
  "Lasell University",
  "Lawrence University",
  "Le Moyne College",
  "Le Moyne-Owen College",
  "Lebanon Valley College",
  "Lee University",
  "Lehigh University",
  "Lesley University",
  "Lesley University College of Art and Design",
  "Lewis & Clark College",
  "Lewis University",
  "Lewis-Clark State College",
  "Liberty University",
  "Lincoln University (MO)",
  "Lincoln University (PA)",
  "Lindenwood University",
  "Linfield University",
  "Lipscomb University",
  "Livingstone College",
  "Lock Haven University",
  "Loma Linda University",
  "Long Island University",
  "Longwood University",
  "Loras College",
  "Louisiana State University (LSU)",
  "Loyola Marymount University",
  "Loyola University Chicago",
  "Loyola University Maryland",
  "Loyola University New Orleans",
  "Luther College",
  "Lycoming College",
  "Lyndon State College",
  "Lynn University",
  "Lyon College",
  "Macalester College",
  "Manchester University",
  "Manhattan College",
  "Manhattan School of Music",
  "Mansfield University",
  "Marian University (IN)",
  "Marian University (WI)",
  "Marietta College",
  "Marist College",
  "Marlboro College",
  "Marquette University",
  "Maryland Institute College of Art (MICA)",
  "Marymount California University",
  "Maryville College",
  "Maryville University",
  "Marywood University",
  "Massachusetts College of Art and Design",
  "Massachusetts Institute of Technology (MIT)",
  "Massachusetts Maritime Academy",
  "Mayville State University",
  "McDaniel College",
  "McKendree University",
  "McMurry University",
  "McPherson College",
  "Menlo College",
  "Mercer University",
  "Mercyhurst University",
  "Merrimack College",
  "Messiah University",
  "Metropolitan State University of Denver",
  "Michigan State University",
  "Michigan Technological University",
  "Middle Georgia State University",
  "Middlebury College",
  "Midwestern State University",
  "Miles College",
  "Millersville University",
  "Millikin University",
  "Mills College",
  "Millsaps College",
  "Milwaukee School of Engineering",
  "Minneapolis College of Art and Design",
  "Minnesota State University Mankato",
  "Minnesota State University Moorhead",
  "Minot State University",
  "Misericordia University",
  "Mississippi State University",
  "Mississippi Valley State University",
  "Missouri Southern State University",
  "Missouri State University",
  "Missouri University of Science and Technology",
  "Missouri Valley College",
  "Missouri Western State University",
  "Mitchell College",
  "Molloy University",
  "Monmouth College (IL)",
  "Monmouth University",
  "Montana State University",
  "Montana State University Billings",
  "Montana Tech",
  "Montclair State University",
  "Moore College of Art and Design",
  "Moravian University",
  "Morehouse College",
  "Morgan State University",
  "Morningside University",
  "Mount Holyoke College",
  "Mount Mercy University",
  "Mount Saint Mary's University (CA)",
  "Mount St. Mary's University (MD)",
  "Muhlenberg College",
  "Muskingum University",
  "National University",
  "Nazareth University",
  "Nebraska Wesleyan University",
  "Neumann University",
  "New England Conservatory",
  "New Jersey City University",
  "New Jersey Institute of Technology (NJIT)",
  "New Mexico Highlands University",
  "New Mexico Institute of Mining and Technology",
  "New Mexico State University",
  "New York Institute of Technology (NYIT)",
  "New York University (NYU)",
  "Newberry College",
  "Niagara University",
  "Nichols College",
  "Norfolk State University",
  "North Carolina A&T State University",
  "North Carolina Central University",
  "North Carolina State University",
  "North Central College",
  "North Central University",
  "North Dakota State University",
  "North Park University",
  "Northeastern State University",
  "Northeastern University",
  "Northern Arizona University",
  "Northern Illinois University",
  "Northern Michigan University",
  "Northern State University",
  "Northwest Missouri State University",
  "Northwest Nazarene University",
  "Northwestern College (IA)",
  "Northwestern University",
  "Notre Dame de Namur University",
  "Nova Southeastern University",
  "Oakland University",
  "Oakwood University",
  "Oberlin College",
  "Oberlin Conservatory of Music",
  "Occidental College",
  "Oglethorpe University",
  "Ohio State University",
  "Ohio Wesleyan University",
  "Oklahoma Baptist University",
  "Oklahoma Christian University",
  "Oklahoma City University",
  "Oklahoma State University",
  "Old Dominion University",
  "Oral Roberts University",
  "Oregon Institute of Technology",
  "Oregon State University",
  "Otis College of Art and Design",
  "Ottawa University",
  "Otterbein University",
  "Ouachita Baptist University",
  "Pace University",
  "Pacific Lutheran University",
  "Pacific Northwest College of Art",
  "Pacific University",
  "Paine College",
  "Palm Beach Atlantic University",
  "Park University",
  "Parsons School of Design",
  "Paul Quinn College",
  "Peabody Institute",
  "Penn State University",
  "Pepperdine University",
  "Peru State College",
  "Philander Smith College",
  "Piedmont University",
  "Pittsburg State University",
  "Pitzer College",
  "Plymouth State University",
  "Point Loma Nazarene University",
  "Point Park University",
  "Pomona College",
  "Portland State University",
  "Post University",
  "Prairie View A&M University",
  "Pratt Institute",
  "Presbyterian College",
  "Princeton University",
  "Providence College",
  "Purdue University",
  "Purdue University Fort Wayne",
  "Purdue University Global",
  "Purdue University Northwest",
  "Quincy University",
  "Quinnipiac University",
  "Radford University",
  "Ramapo College",
  "Reed College",
  "Regis University",
  "Rensselaer Polytechnic Institute (RPI)",
  "Rhode Island College",
  "Rhode Island School of Design (RISD)",
  "Rhodes College",
  "Rice University",
  "Rider University",
  "Ringling College of Art and Design",
  "Ripon College",
  "Robert Morris University",
  "Rochester Institute of Technology (RIT)",
  "Rockhurst University",
  "Rocky Mountain College",
  "Roger Williams University",
  "Rollins College",
  "Rose-Hulman Institute of Technology",
  "Rowan University",
  "Rust College",
  "Rutgers University",
  "SUNY Adirondack",
  "SUNY Binghamton University",
  "SUNY Buffalo State University",
  "SUNY Canton",
  "SUNY Cobleskill",
  "SUNY College at Brockport",
  "SUNY College of Environmental Science and Forestry",
  "SUNY Cortland",
  "SUNY Delhi",
  "SUNY Downstate Health Sciences University",
  "SUNY Empire State College",
  "SUNY Fredonia",
  "SUNY Geneseo",
  "SUNY Maritime College",
  "SUNY Morrisville",
  "SUNY New Paltz",
  "SUNY Old Westbury",
  "SUNY Oneonta",
  "SUNY Oswego",
  "SUNY Plattsburgh",
  "SUNY Polytechnic Institute",
  "SUNY Potsdam",
  "SUNY Purchase College",
  "SUNY Stony Brook University",
  "SUNY University at Albany",
  "SUNY University at Buffalo",
  "SUNY Upstate Medical University",
  "Sacramento State University",
  "Sacred Heart University",
  "Saginaw Valley State University",
  "Saint Augustine's University",
  "Saint John's University (MN)",
  "Saint Leo University",
  "Saint Louis University",
  "Saint Martin's University",
  "Saint Mary's College of California",
  "Saint Peter's University",
  "Salem State University",
  "Salisbury University",
  "Salve Regina University",
  "Sam Houston State University",
  "Samford University",
  "San Diego State University (SDSU)",
  "San Francisco Conservatory of Music",
  "San Francisco State University",
  "San Jose State University",
  "Santa Clara University",
  "Sarah Lawrence College",
  "Savannah College of Art and Design (SCAD)",
  "Savannah State University",
  "School of Visual Arts (SVA)",
  "School of the Art Institute of Chicago (SAIC)",
  "Schreiner University",
  "Scripps College",
  "Seattle Pacific University",
  "Seattle University",
  "Seton Hall University",
  "Sewanee: The University of the South",
  "Shaw University",
  "Shippensburg University",
  "Shorter University",
  "Siena College",
  "Sierra Nevada University",
  "Simpson College",
  "Simpson University",
  "Skidmore College",
  "Slippery Rock University",
  "Smith College",
  "Sonoma State University",
  "South Carolina State University",
  "South Dakota State University",
  "Southeast Missouri State University",
  "Southeastern Oklahoma State University",
  "Southeastern University",
  "Southern Connecticut State University",
  "Southern Illinois University Carbondale",
  "Southern Illinois University Edwardsville",
  "Southern Methodist University (SMU)",
  "Southern New Hampshire University",
  "Southern Oregon University",
  "Southern University",
  "Southern Utah University",
  "Southwest Minnesota State University",
  "Southwestern Oklahoma State University",
  "Southwestern University",
  "Spelman College",
  "Spring Arbor University",
  "Spring Hill College",
  "Springfield College",
  "St. Ambrose University",
  "St. Bonaventure University",
  "St. Cloud State University",
  "St. Edward's University",
  "St. John's University",
  "St. Joseph's College (NY)",
  "St. Joseph's University",
  "St. Lawrence University",
  "St. Mary's College of Maryland",
  "St. Mary's University (TX)",
  "St. Norbert College",
  "St. Olaf College",
  "Stanford University",
  "Stephen F. Austin State University",
  "Sterling College",
  "Stetson University",
  "Stevens Institute of Technology",
  "Stevenson University",
  "Stillman College",
  "Stockton University",
  "Stonehill College",
  "Strayer University",
  "Suffolk University",
  "Sul Ross State University",
  "Susquehanna University",
  "Swarthmore College",
  "Syracuse University",
  "Tabor College",
  "Talladega College",
  "Tarleton State University",
  "Taylor University",
  "Temple University",
  "Tennessee State University",
  "Texas A&M International University",
  "Texas A&M University",
  "Texas A&M University-Commerce",
  "Texas A&M University-Corpus Christi",
  "Texas A&M University-Kingsville",
  "Texas A&M University-San Antonio",
  "Texas A&M University-Texarkana",
  "Texas Christian University (TCU)",
  "Texas Southern University",
  "Texas State University",
  "Texas Tech University",
  "Texas Woman's University",
  "The Citadel",
  "The College of New Jersey",
  "The New School",
  "Thomas Edison State University",
  "Thomas More University",
  "Tougaloo College",
  "Touro University",
  "Towson University",
  "Transylvania University",
  "Trine University",
  "Trinity College (CT)",
  "Trinity University",
  "Truman State University",
  "Tufts University",
  "Tulane University",
  "Tuskegee University",
  "Tyler School of Art and Architecture",
  "UMBC (University of Maryland, Baltimore County)",
  "UNC Asheville",
  "UNC Charlotte",
  "UNC Greensboro",
  "UNC Pembroke",
  "UNC Wilmington",
  "Union College (NY)",
  "Union University",
  "United States Air Force Academy",
  "United States Coast Guard Academy",
  "United States Merchant Marine Academy",
  "United States Military Academy (West Point)",
  "United States Naval Academy",
  "University of Alabama",
  "University of Alaska Anchorage",
  "University of Alaska Fairbanks",
  "University of Alaska Southeast",
  "University of Arizona",
  "University of Arkansas",
  "University of Arkansas at Pine Bluff",
  "University of Baltimore",
  "University of Bridgeport",
  "University of California, Berkeley",
  "University of California, Davis",
  "University of California, Irvine",
  "University of California, Los Angeles (UCLA)",
  "University of California, Merced",
  "University of California, Riverside",
  "University of California, San Diego (UCSD)",
  "University of California, Santa Barbara (UCSB)",
  "University of California, Santa Cruz",
  "University of Central Florida",
  "University of Central Missouri",
  "University of Central Oklahoma",
  "University of Chicago",
  "University of Colorado Boulder",
  "University of Colorado Colorado Springs",
  "University of Colorado Denver",
  "University of Connecticut",
  "University of Dallas",
  "University of Dayton",
  "University of Delaware",
  "University of Denver",
  "University of Detroit Mercy",
  "University of Dubuque",
  "University of Evansville",
  "University of Florida",
  "University of Georgia",
  "University of Hartford",
  "University of Hawaii at Manoa",
  "University of Houston",
  "University of Idaho",
  "University of Illinois Chicago",
  "University of Illinois Springfield",
  "University of Illinois Urbana-Champaign",
  "University of Indianapolis",
  "University of Iowa",
  "University of Kansas",
  "University of Kentucky",
  "University of La Verne",
  "University of Maine",
  "University of Maine at Farmington",
  "University of Maine at Fort Kent",
  "University of Maine at Machias",
  "University of Maine at Presque Isle",
  "University of Mary Hardin-Baylor",
  "University of Mary Washington",
  "University of Maryland Eastern Shore",
  "University of Maryland, College Park",
  "University of Massachusetts Amherst",
  "University of Massachusetts Boston",
  "University of Massachusetts Dartmouth",
  "University of Massachusetts Lowell",
  "University of Miami",
  "University of Michigan",
  "University of Minnesota",
  "University of Minnesota Duluth",
  "University of Mississippi",
  "University of Missouri",
  "University of Missouri-Kansas City",
  "University of Missouri-St. Louis",
  "University of Montana",
  "University of Montana Western",
  "University of Nebraska at Kearney",
  "University of Nebraska at Omaha",
  "University of Nebraska-Lincoln",
  "University of Nevada, Las Vegas (UNLV)",
  "University of Nevada, Reno",
  "University of New Hampshire",
  "University of New Haven",
  "University of New Mexico",
  "University of North Carolina at Chapel Hill",
  "University of North Dakota",
  "University of North Florida",
  "University of North Georgia",
  "University of North Texas",
  "University of Northern Colorado",
  "University of Northern Iowa",
  "University of Notre Dame",
  "University of Oklahoma",
  "University of Oregon",
  "University of Pennsylvania",
  "University of Phoenix",
  "University of Pittsburgh",
  "University of Portland",
  "University of Puget Sound",
  "University of Redlands",
  "University of Rhode Island",
  "University of Richmond",
  "University of Rochester",
  "University of Saint Francis (IN)",
  "University of Saint Joseph (CT)",
  "University of San Diego",
  "University of San Francisco",
  "University of Science and Arts of Oklahoma",
  "University of Scranton",
  "University of South Carolina",
  "University of South Dakota",
  "University of South Florida",
  "University of Southern California (USC)",
  "University of Southern Indiana",
  "University of Southern Maine",
  "University of St. Thomas (MN)",
  "University of Tampa",
  "University of Tennessee, Knoxville",
  "University of Texas Permian Basin",
  "University of Texas Rio Grande Valley",
  "University of Texas Tyler",
  "University of Texas at Arlington",
  "University of Texas at Austin",
  "University of Texas at Dallas",
  "University of Texas at El Paso",
  "University of Texas at San Antonio",
  "University of Tulsa",
  "University of Utah",
  "University of Vermont",
  "University of Virginia",
  "University of Washington",
  "University of West Florida",
  "University of Wisconsin-Eau Claire",
  "University of Wisconsin-Green Bay",
  "University of Wisconsin-La Crosse",
  "University of Wisconsin-Madison",
  "University of Wisconsin-Milwaukee",
  "University of Wisconsin-Oshkosh",
  "University of Wisconsin-Parkside",
  "University of Wisconsin-Platteville",
  "University of Wisconsin-River Falls",
  "University of Wisconsin-Stevens Point",
  "University of Wisconsin-Stout",
  "University of Wisconsin-Superior",
  "University of Wisconsin-Whitewater",
  "University of Wyoming",
  "University of the District of Columbia",
  "University of the Incarnate Word",
  "University of the Pacific",
  "University of the Virgin Islands",
  "Upper Iowa University",
  "Ursinus College",
  "Utah State University",
  "Utah Valley University",
  "Utica University",
  "Valdosta State University",
  "Valley City State University",
  "Valparaiso University",
  "Vanderbilt University",
  "Vanguard University",
  "Vassar College",
  "Villanova University",
  "Virginia Commonwealth University",
  "Virginia State University",
  "Virginia Tech",
  "Virginia Union University",
  "Viterbo University",
  "Voorhees College",
  "Wabash College",
  "Wagner College",
  "Wake Forest University",
  "Walden University",
  "Walla Walla University",
  "Wartburg College",
  "Washburn University",
  "Washington College",
  "Washington State University",
  "Washington University in St. Louis",
  "Washington and Lee University",
  "Wayne State College",
  "Wayne State University",
  "Webb Institute",
  "Weber State University",
  "Webster University",
  "Wellesley College",
  "Wentworth Institute of Technology",
  "Wesleyan University",
  "West Chester University",
  "West Texas A&M University",
  "West Virginia State University",
  "West Virginia University",
  "Western Carolina University",
  "Western Colorado University",
  "Western Connecticut State University",
  "Western Governors University",
  "Western Illinois University",
  "Western Michigan University",
  "Western New England University",
  "Western New Mexico University",
  "Western Oregon University",
  "Western Washington University",
  "Westfield State University",
  "Westminster College (UT)",
  "Westmont College",
  "Wheaton College (IL)",
  "Wheaton College (MA)",
  "Whitman College",
  "Whittier College",
  "Whitworth University",
  "Wichita State University",
  "Widener University",
  "Wilberforce University",
  "Wiley College",
  "Willamette University",
  "William Jessup University",
  "William Jewell College",
  "William Paterson University",
  "William Penn University",
  "Williams College",
  "Winona State University",
  "Winston-Salem State University",
  "Winthrop University",
  "Wittenberg University",
  "Wofford College",
  "Woodbury University",
  "Worcester Polytechnic Institute (WPI)",
  "Worcester State University",
  "Xavier University",
  "Xavier University of Louisiana",
  "Yale University",
  "Yeshiva University",
  "Young Harris College",
  "Other",
];

export const OnboardingAcademics = ({ onNext, onBack, initialData }: OnboardingAcademicsProps) => {
  const [academics, setAcademics] = useState<AcademicData>({
    university: initialData?.university || "",
    degree: initialData?.degree || "",
    major: initialData?.major || "",
    graduationMonth: initialData?.graduationMonth || "",
    graduationYear: initialData?.graduationYear || "",
  });
  const [open, setOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onNext(academics);
  };

  const currentYear = new Date().getFullYear();
  const years = Array.from({ length: 20 }, (_, i) => currentYear - 10 + i);
  const months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ];

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-12 items-start px-4">
      <div className="space-y-8">
        <div className="space-y-6">
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-foreground">
            Academic <span className="bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">Information</span>
          </h2>
          <p className="text-lg md:text-xl text-muted-foreground leading-relaxed">
            Tell us about your educational background to help us find the best opportunities for you.
          </p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6 mt-8 lg:mt-12">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <Label htmlFor="university" className="text-foreground font-medium">University/College</Label>
              <Popover open={open} onOpenChange={setOpen}>
                <PopoverTrigger asChild>
                  <Button
                    variant="outline"
                    role="combobox"
                    aria-expanded={open}
                    className="w-full justify-between h-10 px-3 py-2"
                  >
                    {academics.university || "Select university..."}
                    <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-full p-0" align="start">
                  <Command>
                    <CommandInput 
                      placeholder="Search or type your university..." 
                      className="h-9"
                      onValueChange={(search) => {
                        setSearchQuery(search);
                      }}
                    />
                    <CommandList className="max-h-[200px]">
                      <CommandEmpty>
                        <button
                          className="w-full text-left px-2 py-1.5 text-sm cursor-pointer hover:bg-accent rounded-sm"
                          onMouseDown={(e) => {
                            e.preventDefault();
                            setAcademics(prev => ({ ...prev, university: searchQuery }));
                            setOpen(false);
                          }}
                        >
                          Use "<span className="font-medium">{searchQuery}</span>" as your university
                        </button>
                      </CommandEmpty>
                      <CommandGroup>
                        {universities.map((university) => (
                          <CommandItem
                            key={university}
                            value={university}
                            onSelect={(currentValue) => {
                              setAcademics(prev => ({ 
                                ...prev, 
                                university: currentValue === academics.university ? "" : currentValue 
                              }));
                              setOpen(false);
                            }}
                          >
                            <Check
                              className={cn(
                                "mr-2 h-4 w-4",
                                academics.university === university ? "opacity-100" : "opacity-0"
                              )}
                            />
                            {university}
                          </CommandItem>
                        ))}
                      </CommandGroup>
                    </CommandList>
                  </Command>
                </PopoverContent>
              </Popover>
            </div>

            <div className="space-y-2">
              <Label htmlFor="degree" className="text-foreground font-medium">Degree Level</Label>
              <Select value={academics.degree} onValueChange={(value) => setAcademics(prev => ({ ...prev, degree: value }))}>
                <SelectTrigger>
                  <SelectValue placeholder="Select degree level" />
                </SelectTrigger>
                <SelectContent className="bg-background border z-50">
                  <SelectItem value="associate">Associate's Degree</SelectItem>
                  <SelectItem value="bachelor">Bachelor's Degree</SelectItem>
                  <SelectItem value="master">Master's Degree</SelectItem>
                  <SelectItem value="doctoral">Doctoral Degree</SelectItem>
                  <SelectItem value="certificate">Certificate</SelectItem>
                  <SelectItem value="other">Other</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <Label htmlFor="graduationMonth" className="text-foreground font-medium">Graduation Month</Label>
              <Select value={academics.graduationMonth} onValueChange={(value) => setAcademics(prev => ({ ...prev, graduationMonth: value }))}>
                <SelectTrigger>
                  <SelectValue placeholder="Select graduation month" />
                </SelectTrigger>
                <SelectContent className="bg-background border z-50">
                  {months.map((month) => (
                    <SelectItem key={month} value={month.toLowerCase()}>
                      {month}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="graduationYear" className="text-foreground font-medium">Graduation Year</Label>
              <Select value={academics.graduationYear} onValueChange={(value) => setAcademics(prev => ({ ...prev, graduationYear: value }))}>
                <SelectTrigger>
                  <SelectValue placeholder="Select graduation year" />
                </SelectTrigger>
                <SelectContent className="bg-background border z-50">
                  {years.map((year) => (
                    <SelectItem key={year} value={year.toString()}>
                      {year}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="major" className="text-foreground font-medium">Major/Field of Study</Label>
            <Input
              id="major"
              value={academics.major}
              onChange={(e) => setAcademics(prev => ({ ...prev, major: e.target.value }))}
              placeholder="Enter your major"
              required
            />
          </div>


          <div className="flex justify-between pt-8">
            <Button
              type="button"
              variant="outline"
              onClick={onBack}
              className="px-8 py-3 rounded-full font-semibold"
            >
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back
            </Button>
            
            <Button
              type="submit"
              variant="gradient"
              className="px-12 py-3 rounded-full font-bold group"
            >
              Next
              <ArrowRight className="ml-2 h-4 w-4 group-hover:translate-x-1 transition-transform" />
            </Button>
          </div>
        </form>
      </div>
      
      <div className="hidden lg:flex items-center justify-center">
        <img 
          src={academicIllustration} 
          alt="Academic robot illustration" 
          className="w-full max-w-md h-auto object-contain"
        />
      </div>
    </div>
  );
};